"""initial_schema

Revision ID: 96f6b01d61c4
Revises:
Create Date: 2026-10-03 13:09:17.759265

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "96f6b01d61c4"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tenants",
        sa.Column("id", sa.String(length=128), nullable=False),
        sa.Column("business_name", sa.String(length=255), nullable=False),
        sa.Column("default_language", sa.String(length=32), nullable=False),
        sa.Column("supported_languages", sa.String(length=255), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "call_records",
        sa.Column("call_id", sa.String(length=128), nullable=False),
        sa.Column("tenant_id", sa.String(length=128), nullable=False),
        sa.Column("language", sa.String(length=32), nullable=False),
        sa.Column("turn_count", sa.Integer(), nullable=False),
        sa.Column("handoff_required", sa.Boolean(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("call_id"),
    )
    op.create_index(
        op.f("ix_call_records_tenant_id"), "call_records", ["tenant_id"], unique=False
    )
    op.create_table(
        "faqs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("tenant_id", sa.String(length=128), nullable=False),
        sa.Column("faq_key", sa.String(length=128), nullable=False),
        sa.Column("question", sa.Text(), nullable=False),
        sa.Column("answers_json", sa.Text(), nullable=False),
        sa.Column("aliases_json", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "faq_key", name="uq_faq_tenant_key"),
    )
    op.create_index(op.f("ix_faqs_tenant_id"), "faqs", ["tenant_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_faqs_tenant_id"), table_name="faqs")
    op.drop_table("faqs")
    op.drop_index(op.f("ix_call_records_tenant_id"), table_name="call_records")
    op.drop_table("call_records")
    op.drop_table("tenants")
    # ### end Alembic commands ###
