"""post_call_outcomes_and_leads

Revision ID: a0371bd0e5e9
Revises: 778ce8253f2a
Create Date: 2026-10-03 13:28:53.827446

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a0371bd0e5e9"
down_revision: str | Sequence[str] | None = "778ce8253f2a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "call_outcomes",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=128), nullable=False),
        sa.Column("call_id", sa.String(length=128), nullable=False),
        sa.Column("transcript", sa.Text(), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("turn_count", sa.Integer(), nullable=False),
        sa.Column("handoff_required", sa.Boolean(), nullable=False),
        sa.Column("caller_name", sa.String(length=255), nullable=True),
        sa.Column("caller_phone", sa.String(length=64), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "call_id", name="uq_call_outcome_tenant_call"),
    )
    op.create_index(
        op.f("ix_call_outcomes_call_id"), "call_outcomes", ["call_id"], unique=False
    )
    op.create_index(
        op.f("ix_call_outcomes_tenant_id"), "call_outcomes", ["tenant_id"], unique=False
    )
    op.create_table(
        "leads",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=128), nullable=False),
        sa.Column("call_id", sa.String(length=128), nullable=False),
        sa.Column("caller_name", sa.String(length=255), nullable=True),
        sa.Column("caller_phone", sa.String(length=64), nullable=False),
        sa.Column("interest", sa.String(length=500), nullable=True),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "call_id", name="uq_lead_tenant_call"),
    )
    op.create_index(op.f("ix_leads_call_id"), "leads", ["call_id"], unique=False)
    op.create_index(op.f("ix_leads_tenant_id"), "leads", ["tenant_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_leads_tenant_id"), table_name="leads")
    op.drop_index(op.f("ix_leads_call_id"), table_name="leads")
    op.drop_table("leads")
    op.drop_index(op.f("ix_call_outcomes_tenant_id"), table_name="call_outcomes")
    op.drop_index(op.f("ix_call_outcomes_call_id"), table_name="call_outcomes")
    op.drop_table("call_outcomes")
    # ### end Alembic commands ###
